name: clean_project
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  # Service locator
  get_it: ^5.0.6
  # Value equality
  equatable: ^1.2.6
  #Remote API
  http: ^0.12.2
  # Local cache
  shared_preferences: 0.5.12+4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
